id: 19f361c884014c5a96e52f8bded3d366
initial_creation_type: ebook
created_at: 27/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: tt
  cover: tmp6ue2jd85.jpg
  credit: tmpuf8tib6r.jpg
